### ISSUE TITLE
UI Feedback from Nedbank team on home page - part 2

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#111]
See here https://www.figma.com/file/wjOA2PNgpfOIxryT7BFlZC/Design-critique---Untitled?node-id=387-19&t=m8Z29EOXE7j1M8Mx-0

**Comment by bosschaert** [comment]
As there are a lot of suggestions on the critique I came up with a numbering scheme so we can address each individually. Number is per column and then per issue on that column left-to-right row-by-row

1a: hamburger icon centering
1b: icon placement to left of hamburger
1c: dropdown styling
1d: small arrow hover direction
1e: nav item hover background
1f: missing drop shadown on header intro
1g: content intro drop shadow

2a: ...

**Comment by bosschaert** [comment]
This comment is used to track which of the issues mentioned above are addressed:

```
1a:    2a:    3a: ✓
1b:    2b:    3b:
1c:           3c:
1d:           3d:
1e:           3e:
1f:
1g:
```
