### ISSUE TITLE
Prevent requests made to /libs/granite/csrf/token.json

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#142]
![image](https://user-images.githubusercontent.com/1191451/228192724-d6cbf195-2812-4338-b098-6a099344211d.png)

**Comment by jindaliiita** [comment]
We need to remove call to http://nedbanklimited.tt.omtrdc.net/rest/v1/delivery
See below issue
https://github.com/hlxsites/nedbank/issues/170

Also check conversation at https://cq-dev.slack.com/archives/C04PFD5A4B1/p1680287170227979

**Comment by hparwani2** [comment]
https://github.com/hlxsites/nedbank/issues/170, will be catered in different PR

**Comment by sdmcraft** [comment]
@hparwani2 is there anything pending besides the fix you did via https://github.com/hlxsites/nedbank/commit/bd44f9492d021fa70d49d5c35bbf19a064dad776 ?
