### ISSUE TITLE
Styling issue home page small screen

### ISSUE THREAD

**Issue by jindaliiita** [hlxsites/nedbank#143]
Observing styling issues for almost all sections for home page.
Attaching Screenshot for 450px screen size but issues are there for screen size 1000px also.

**Franklin**
1: <img width="1728" alt="hero_block_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204941-cf18023a-3aa9-4a04-937c-26b2fe89f031.png">
2: <img width="1728" alt="homebanner_and_services_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204956-db87d6d8-00e3-49cf-bf35-4a032edd3c5f.png">
3: <img width="1728" alt="columns_container_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204966-f7966c8d-cfee-4fdb-b24a-a585b59a6575.png">
4: <img width="1728" alt="promotions_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204974-8b630c91-8df3-4bbc-889f-f3ba29c24b55.png">
5: <img width="1728" alt="switchcard_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204980-e49e18ac-2994-4742-b0f0-a380d7bfe22a.png">
6: <img width="1728" alt="footer_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204982-40fc5540-93a9-44d4-b4f2-56cb92f8202f.png">
7: <img width="1728" alt="navbar_and_banner_franklin_450px" src="https://user-images.githubusercontent.com/12638407/228204912-79d3cb52-1618-47e0-bb4a-b4d571527642.png">

-----------------------------------
**Reference site**

<img width="1728" alt="navbar_and_banner_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205175-832d0c9f-9032-44fd-91e8-a1ea094713ff.png">
<img width="1728" alt="hero_block_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205208-968933dd-d3c8-4eaf-b915-9ffbf02977a7.png">
<img width="1728" alt="homebanner_and_services_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205217-5f09818b-9049-46ec-a8fa-5f2a16d68b99.png">
<img width="1728" alt="columns_container_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205223-a9bfd4c5-6542-4301-a271-bf3be4d11414.png">
<img width="1728" alt="promotions_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205233-c6e721e6-1214-43ca-9b14-e1fdcaf7682e.png">
<img width="1728" alt="switchcard_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205239-8aa0f4fa-9401-4afb-8413-c774c373b2f8.png">
<img width="1728" alt="footer_actual_450px" src="https://user-images.githubusercontent.com/12638407/228205241-62f5026b-63bb-4561-8ea4-4c70af25a5a0.png">

**Comment by bosschaert** [comment]
In this comment we can keep track of the individual sub-issues:
`✓ = done, . = PR, * = see notes`

```
1:    4:    7:
2:    5:
3:    6:
```
