### ISSUE TITLE
Fade in hero and home-banner text

### ISSUE THREAD

**Issue by bosschaert** [hlxsites/nedbank#158]
For the desired fade-in effect see https://framer.com/share/fzlyk4YPeMtC8VhCHpxy/S0Hd808v0?highlights=0#S0Hd808v0 (the fonts and other design details of this page can be ignored)

**Comment by jindaliiita** [comment]
Don't have access to the framer screen

**Comment by sdmcraft** [comment]
> Don't have access to the framer screen

Try with Safari if it works.
