### ISSUE TITLE
Back button hidden in hamburger in mobile view

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#166]
Current
![image](https://user-images.githubusercontent.com/1191451/229126345-9c029930-9caa-4b82-9076-f91df90583fd.png)

Desired 
![image](https://user-images.githubusercontent.com/1191451/229126524-ce8afaf9-9162-4ce3-b795-3e1ab5540d57.png)

**Comment by jindaliiita** [comment]
@sdmcraft I am not seeing desired style anywhere (Figma, Invision and Nedbank Website).
From where u have referred this design ?

**Comment by sdmcraft** [comment]
> @sdmcraft I am not seeing desired style anywhere (Figma, Invision and Nedbank Website). From where u have referred this design ?

Saw it on reference site 

https://user-images.githubusercontent.com/1191451/230855386-160c190b-f12f-4228-8277-9cd2bc15355f.mov
