### ISSUE TITLE
Address js error while loading home page

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#177]
Following error is seen while loading the home page
```
clientlibs.min.js:58 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at HTMLDocument.<anonymous> (clientlibs.min.js:58:83)
    at k (jquery.min.js:99:93)
    at Object.fireWith [as resolveWith] (jquery.min.js:100:343)
    at ready (jquery.min.js:104:123)
```

**Comment by vdua** [comment]
@sdmcraft I am seeing a different error

```
clientlibs.min.js:46 Uncaught TypeError: Cannot read properties of undefined (reading 'top')
    at HTMLDocument.<anonymous> (clientlibs.min.js:46:109)
    at k (jquery.min.js:99:93)
    at Object.add [as done] (jquery.min.js:99:380)
    at c.fn.ready (jquery.min.js:103:425)
    at clientlibs.min.js:46:13
```

The clientlib is huge and that particular code is not required. It tries to provide the sticky position to the top dropdown menu

<img width="531" alt="image" src="https://user-images.githubusercontent.com/2097597/230890219-51920d83-3f12-4433-892a-252b3f726a40.png">

Any idea how we can remove only a subset of the code from the clientlib ?

**Comment by sdmcraft** [comment]
> Any idea how we can remove only a subset of the code from the clientlib ?

If that clientlib is not needed, maybe we can omit it altogether. Other option is to copy it over and retain only the parts needed. Eventually I think we should get rid of the clientlib altogether.
