### ISSUE TITLE
Prevent FOUC with nav search on slow network

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#204]
Currently there's a FOUC (flash-of-unstyled-content) for a few seconds when the search menu is opened on a slow 3g connection. Attaching a video capturing the same. This ticket is logged to prevent this. One possible solution could be along the lines of keeping the external-markup (including search markup which is fetched from Nedbank) hidden till all the styles have been loaded.

https://user-images.githubusercontent.com/1191451/232548933-f5abf31b-44d8-4615-9f08-c2fab0c432ea.mov

**Comment by jindaliiita** [comment]
@sdmcraft I have created a draft PR for this issue
On a slow network, the clientlibs-site.css file may not fully download, causing an intermediate state to occur when the Search button is clicked. Possible solutions to this issue:

1. Moving all clientlibs.css files to the head.html file, as has been done in the draft PR "https://github.com/hlxsites/nedbank/pull/211". However, this may impact the LHS.
2. Splitting the clientlibs.css file into multiple smaller files and removing unnecessary code to improve loading speed. This is a somewhat tedious task.
3. Disabling the search overlay until the clientlibs.css file is fully loaded, but this requires using the window.load event.

None of these solutions seem ideal to me. Let me know if you have a better solution.
cc @hparwani2 @vdua @bosschaert

**Comment by sdmcraft** [comment]
What's the impact of option 1 on LHS? It looks the simplest.

Option 2 seems tedious as you say and its not definite that it going to resolve the problem I think.

Option 3 looks promising to me but I am not sure we can rely on `window.load` event as these `css` are fetched via js execution and not part of the initial markup. Could you check this? In the absence of this event, we could look at loading the external css synchronously and keep the `#external-markup`element hidden till that completes. I found a related [SO discussion on this](https://stackoverflow.com/questions/35644072/dynamically-load-css-stylesheet-and-wait-for-it-to-load). Please see if it helps.
