### ISSUE TITLE
Address header ordering items for improving accessibility score

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#219]

**Comment by jindaliiita** [comment]
@sdmcraft There is one more contrast point regarding to primary nav items by which Score can be increased.
This also leads to distorted colour combination of website.

<img width="1728" alt="Screenshot 2023-04-26 at 9 57 16 AM" src="https://user-images.githubusercontent.com/12638407/234470106-c63873d3-cefc-4493-b79c-ddb290264a45.png">
