### ISSUE TITLE
Normalize responsive layout breakpoints

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#36]
Currently the media query breakpoints are a bit scattered around [as indicated here](https://github.com/hlxsites/nedbank/search?l=CSS&q=media). Logging this issue to consolidate them at single place and use them as variables across stylesheets.

**Comment by hparwani2** [comment]
Breakpoints has been converted to mobile-first design, creating new issue for reducing the widths (https://github.com/hlxsites/nedbank/issues/42)
