### ISSUE TITLE
Aggregate "digitalData" for analytics

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#73]
On https://personal.nedbank.co.za/home.html , if you open up chrome tools, you'd see a "digitalData" object is present

![image](https://user-images.githubusercontent.com/1191451/221168055-e8fe9952-debf-4571-8b27-21df263dd244.png)

This is used for analytics purposes. We need to build similar "digitalData" object for the Nedbank home page in Franklin. 
Suggested steps:

1. Prepare a spreadsheet with the digital data and url.
2. Use it to build the digital data in front end.
3. This "digitalData" object must be present before the analytics scripts are loaded since they need this data to send to analytics.

**Comment by jindaliiita** [comment]
@sdmcraft digitalData contains all fields other than internalSearch and calculator.
These have to be added on specific pages (Could not be part of delayed.js).
