### ISSUE TITLE
Add `data-*` attributes for analytics

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#74]
Related discussion https://adobe-dx-support.slack.com/archives/C03GY8A76KT/p1677236975034569
More details awaited on this from Nedbank.

**Comment by jindaliiita** [comment]
@sdmcraft There are two concerns here
1. Logic which we discussed in the last call is not applicable to all types of anchor tag.
2. Also Arrows are anchor tag on main website but on our side they are svgs. So, can i apply data-link properties to them ?

**Comment by sdmcraft** [comment]
> * Logic which we discussed in the last call is not applicable to all types of anchor tag.
I think to start with, the general rule is to look up the ancestors and find the nearest heading elements in them and take them as data attributes. For specific cases which do not fit this logic, we can seek feedback from the customer.

> * Also Arrows are anchor tag on main website but on our side they are svgs. So, can i apply data-link properties to them ?
We can wrap the svgs in anchor tags.
