### ISSUE TITLE
Address homepage styling issues

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#87]
Reference page: https://personal.nedbank.co.za/home.html
Franklin page: https://main--nedbank--hlxsites.hlx.page/content/nedbank/za/en/personal/home

List of issues to be addressed

- Navbar background share cropped 
![image](https://user-images.githubusercontent.com/1191451/224951459-6359df42-1d3b-4c8c-be70-7655088a548a.png)

- Incorrect banner shade 
![image](https://user-images.githubusercontent.com/1191451/224951640-13b91f83-7464-47ff-be56-7807e9c8d3ca.png)

- Incorrect text font and style
![image](https://user-images.githubusercontent.com/1191451/224952556-e7b99350-2773-4374-9171-14b64f4b6c36.png)

- Align footer style
![image](https://user-images.githubusercontent.com/1191451/224953403-fc0f5ad1-4c7a-4008-8bc1-ac7452187a56.png)
![image](https://user-images.githubusercontent.com/1191451/224953569-d2fe306c-c2ae-4ef9-a36e-db9c2cc93c45.png)

**Comment by jindaliiita** [comment]
DropDown Designing 
Franklin -
<img width="1728" alt="dropdown_franklin" src="https://user-images.githubusercontent.com/12638407/225208382-d49f355c-1cd3-48ce-9ae7-352ac1c7b01f.png">

Main Website-
<img width="1728" alt="dropdown_main" src="https://user-images.githubusercontent.com/12638407/225208412-e0dacada-6bfb-44ca-8f49-d178fa067ddf.png">

**Comment by bosschaert** [comment]
Reopening as there were still some remaining issues flagged here.
