### ISSUE TITLE
Investigate impact of 3rd party scripts in lowering LHS score

### ISSUE THREAD

**Issue by sdmcraft** [hlxsites/nedbank#99]
The LHS score seems to be getting impacted due to 3rd party analytics scripts. This ticket is logged to investigate and resolve this impact.

LHS without 3P code
https://issue-99--nedbank--hlxsites.hlx.page/
![image](https://user-images.githubusercontent.com/1191451/225383087-cd65ea09-6f67-4c62-9340-3a5fa26dea07.png)

LHS with 3P code
https://main--nedbank--hlxsites.hlx.page/
![image](https://user-images.githubusercontent.com/1191451/225383564-f4cbe2af-f97d-41cf-8e0e-4f210efcb4f6.png)

**Comment by jindaliiita** [comment]
Discussion link - https://cq-dev.slack.com/archives/C04PFD5A4B1/p1679403966083339
As per discussion and analysis done, third party JS is only impacting .page path but not .live path.
Redirection also impacts LHS score negatively.
So, creating a separate issue.
Issue - https://github.com/hlxsites/nedbank/issues/118
